---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-operator-serviceaccount
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ray-operator-role
rules:
- apiGroups: ["", "cluster.ray.io"]
  resources: ["rayclusters", "rayclusters/finalizers", "rayclusters/status", "pods", "pods/exec", "services"]
  verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ray-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: ray-operator-serviceaccount
roleRef:
  kind: Role
  name: ray-operator-role
  apiGroup: rbac.authorization.k8s.io
---
# Why is this not a deployment?
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-operator-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray-operator-pod
  template:
    metadata:
      labels:
        app: ray-operator-pod
    spec:
      serviceAccountName: ray-operator-serviceaccount
      containers:
      - name: ray
        imagePullPolicy: Always
        image: 709156019088.dkr.ecr.us-west-2.amazonaws.com/ray-transformers:latest
        command: ["ray-operator"]
        env:
        - name: RAY_OPERATOR_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            memory: 2Gi
